name: Create Publish Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag crickitycrick/cloud-app:${{ github.run_number }}

    - name: Publish Docker Image
      run: docker push crickitycrick/cloud-app:${{ github.run_number }}

    - name: Trigger Kubernetes update
      run: curl -X POST https://b5a2-89-28-75-176.ngrok-free.app/update/${{ github.run_number }}
